### ISSUE TITLE
Add wrappers to the documentation list (Please add your own)

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#11]
- [ ] PHPokeapi https://github.com/n1c0l4stournier/PHPokeAPI
- [ ] Poke node https://github.com/hemphillcc/pokenode

**Comment by stephantabor** [comment]
node - https://www.npmjs.com/package/pkmn

**Comment by darol100** [comment]
I have a Drupal project that integrate with Pokeapi.

https://www.drupal.org/project/pokeapi

**Comment by williamn** [comment]
Another PHP wrapper https://github.com/williamn/pokeapi-php
