### ISSUE TITLE
v2 magikarp returns 502 error

### ISSUE THREAD

**Issue by gasolinewaltz** [phalt/pokeapi#115]
The following urls return a 502 Bad Gateway error:

[http://pokeapi.co/api/v2/pokemon/magikarp](http://pokeapi.co/api/v2/pokemon/magikarp)
[http://pokeapi.co/api/v2/pokemon/129](http://pokeapi.co/api/v2/pokemon/129 )
[http://pokeapi.co/api/v2/pokemon-species/magikarp](http://pokeapi.co/api/v2/pokemon-species/magikarp)
[http://pokeapi.co/api/v2/pokemon-species/129](http://pokeapi.co/api/v2/pokemon-species/129)

I did some searching on the repo but I wasn't able to find anything. I'll do a local install and try to find the source of the bug, but I figured I'd throw this up here in the meantime

**Comment by phalt** [comment]
Thanks for noticing these @gasolinewaltz we'll look into them :)

**Comment by zaneadix** [comment]
@gasolinewaltz This appears to not be a problem anymore? I'm able to visit those links just fine. Can you check this out again and see if things are working for you?

**Comment by gasolinewaltz** [comment]
@zaneadix It appears to be working now. Thanks!

**Comment by phalt** [comment]
@zaneadix @gasolinewaltz I saw some outages a few days ago and doubled the size of the server. That might have resolved it? ¯\_(ツ)_/¯
