### ISSUE TITLE
Limit and Offset not working

### ISSUE THREAD

**Issue by MaxHasADHD** [phalt/pokeapi#119]
Hey there, I just found this API and it looks great! I am setting up a Paw document for the API (Paw is a HTTP client) and I am trying to see how the Limit and Offset work. I try something like `http://pokeapi.co/api/v2/pokemon/?limit=10&offset=1` but I still get all 784 Pokemon? Shouldn't it return the first 10 pokemon?

**Comment by zaneadix** [comment]
Being tracked in issue #94. Thanks for bringing this to us though @MaxHasADHD. We should hopefully have a fix up for this sometime over the weekend.
