### ISSUE TITLE
Issue endpoint has incorrect description for "held_by_pokemon"

### ISSUE THREAD

**Issue by M-Zuber** [phalt/pokeapi#120]
The documentation for v2 says this regarding the `held_by_pokemon` field on the item endpoint:
![image](https://cloud.githubusercontent.com/assets/4746537/13497267/19605060-e15d-11e5-98eb-179c92545052.png)

While in reality the structure is a bit different:
![image](https://cloud.githubusercontent.com/assets/4746537/13497300/456af9da-e15d-11e5-8f11-913c685341da.png)

**Comment by zaneadix** [comment]
@M-Zuber Whoops. Thanks for pointing this out. Might not be able to fix this before the code push aimed for this weekend but we'll get it done.
