### ISSUE TITLE
baby_trigger_for is incorrectly labeled as being a list (or returned incorrectly as a single object)

### ISSUE THREAD

**Issue by M-Zuber** [phalt/pokeapi#121]
![image](https://cloud.githubusercontent.com/assets/4746537/13501726/779a6dd8-e170-11e5-9bc8-ed502e64a699.png)

I am working on the c# wrapper over at https://gitlab.com/PoroCYon/PokeApi.NET and set up a test that calls every all 746 items.
`baby_trigger_for` does not seem to be an array in any of them.

**Comment by zaneadix** [comment]
@M-Zuber Yeah this is weird. I'll tinker with this too. Thanks again, Mordechai.
