### ISSUE TITLE
Missing definition for EncounterMethodRate

### ISSUE THREAD

**Issue by lodenrogue** [phalt/pokeapi#123]
This object is found under LocationArea. Might also be missing VersionDetails since it's referenced in this object.

**Comment by zaneadix** [comment]
@lodenrogue Could you be more specific? Sounds like your'e saying the parameter isn't being returned on LocationArea resource requests?

**Comment by lodenrogue** [comment]
Sure thing. If you go to this document link: http://pokeapi.co/docsv2/#location-areas you'll see that in LocationArea attribute definitions there is one named encounter_method_rates. This attribute has the data type "list EncounterMethodRate" but EncounterMethodRate is not defined anywhere in the documentation.

**Comment by lodenrogue** [comment]
My mistake. Either it was just added to the documentation or I missed it completely. I see it now.
