### ISSUE TITLE
Moves: mislabeled property

### ISSUE THREAD

**Issue by M-Zuber** [phalt/pokeapi#131]
The docs have the following for the `move` endpoint. Marked is the issue
![image](https://cloud.githubusercontent.com/assets/4746537/13594709/dd1df700-e50e-11e5-92f3-c4d64c46cf61.png)

Per [this page](http://pokeapi.co/docsv2/#super-contest-effects) the second entry should be `super_contest_effect` which is am APIResource(SuperContestEffect).

Proof:
![image](https://cloud.githubusercontent.com/assets/4746537/13594776/6ec48ce6-e50f-11e5-84e2-cb48c185c30a.png)

What skills would I need to just make a PR to the docs?

**Comment by phalt** [comment]
@M-Zuber Just writing skills :) All the documentation is in markdown files!

**Comment by zaneadix** [comment]
@M-Zuber It'd be very much appreciated if you were open to fixing any typos you see as you work. I'm glad you've been diggin really hard and finding all of them :)

https://github.com/phalt/pokeapi/blob/master/templates/pages/docsv2.md

**Comment by M-Zuber** [comment]
Great. I just wasn't up to setting up one of these fancy doc systems. Too much else going on right now, but some markdown I can handle.

Can I do one PR for the 4 issues I've found so far?
