### ISSUE TITLE
Moves: contest_combos is not a list

### ISSUE THREAD

**Issue by M-Zuber** [phalt/pokeapi#132]
Docs:
![image](https://cloud.githubusercontent.com/assets/4746537/13594787/8fbf3108-e50f-11e5-8d13-e913b82e6499.png)

Actual return value:
![image](https://cloud.githubusercontent.com/assets/4746537/13594799/a14ee6a2-e50f-11e5-99dd-92c171907ab0.png)

**Comment by phalt** [comment]
@M-Zuber Heya. Can you point out where it says it should be a list?

**Comment by zaneadix** [comment]
@phalt looks like its just in the docs. Just need to remove the word 'list' in the data-type of the table

**Comment by M-Zuber** [comment]
Sorry that screen shot is quite small :)
