### ISSUE TITLE
Specific species resources are consistently much slower to respond than most

### ISSUE THREAD

**Issue by sargunster** [phalt/pokeapi#137]
I noticed that my app was _always_ timing out when requesting a few specific Pokemon species, but worked fine for requesting the rest. These specific failing Pokemon species remained the same for days. So, I ran some tests and discovered that while most Pokemon species requests are fulfilled in 1-2 seconds, there are fifteen species which _always_ take >10 seconds to respond. Could you possibly look into why these specific resources are so slow? Here is the list:

Endpoint: `/pokemon-species/{id}/`
Slow ids:
 - 19
 - 41
 - 42
 - 72
 - 118
 - 129
 - 130
 - 131
 - 132
 - 133
 - 179
 - 180
 - 530
 - 531
 - 550

**Comment by zaneadix** [comment]
Lol. This sucks. The first one I noticed is Ratatta. Then Zubat and Golbat aaaaaaaand Tentacool. 
Looks like it's pokemon with a lot of encounter locations.
![image](https://cloud.githubusercontent.com/assets/7071557/13718990/d290cdf6-e7bd-11e5-9654-37fc46e30317.png)
 Clearly I've written a horribly slow lookup for the location_area_encounters and everyones favorite pokemon are slapping us in the face for it (I was honestly afraid this would happen).

Maybe a legit pythoner (which I am not) can take a look at this good and help optimize? If I'm honest this could probably done in quite a few places. Moves possibly?

Sorry for the slag @sargunster.

**Comment by sargunster** [comment]
Why not just cache the responses server side since they don't change?

**Comment by zaneadix** [comment]
very true. @phalt any reason why this wouldn't work/is there a particularly efficient way you might know we could do it? My first thought would be to just keep a Dict on the View class

**Comment by sargunster** [comment]
I've never used Django, but maybe it can do the caching for you? 
https://docs.djangoproject.com/en/1.9/topics/cache/

**Comment by phalt** [comment]
It's almost definitely just a timeout problem. We could make the database queries more efficient. I can have a look when I get some spare time in a few weeks, but if anyone wants to jump in, in the mean time go for it.

With Django QuerySets you can reduce the time by doing things like `select_related` to reduce the number of db queries.
