### ISSUE TITLE
no response when missing trailing slash.

### ISSUE THREAD

**Issue by DavidAwad** [phalt/pokeapi#141]
hitting `http://pokeapi.co/api/v2/pokemon/1/` works just fine. 

hitting `http://pokeapi.co/api/v2/pokemon/1` runs forever

**Comment by sargunster** [comment]
I'm getting the following response when I remove the trailing slash:

```
HTTP/1.1 301 MOVED PERMANENTLY
Date: Mon, 14 Mar 2016 06:19:25 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: close
X-Frame-Options: SAMEORIGIN
Location: http://pokeapi.co/api/v2/pokemon/1/
Server: cloudflare-nginx
CF-RAY: 28359d2d7dd3386a-ATL


```
This response seems correct.

**Comment by phalt** [comment]
@DavidAwad yep, you must use trailing slashes. Most modern web browsers do a 301 MOVED PERMENTANTLY to the version with a slash, like in the example response that @sargunster used above.
