### ISSUE TITLE
HTTP not redirecting to HTTPS

### ISSUE THREAD

**Issue by amitburst** [phalt/pokeapi#142]
Looks like you're using CloudFare. If you want users to always use SSL, you can create a "Page rule" for `http://*pokeapi.co*` with the "Always use HTTPS" option turned on. Looks like most or all URLs on the site's documentation use HTTP so I'm not totally sure if this is something you want. :)

**Comment by phalt** [comment]
@amitburst thanks, wasn't sure how to do this :) I'll take a look now
