### ISSUE TITLE
Request header issue with Google Chrome

### ISSUE THREAD

**Issue by vaikan** [phalt/pokeapi#148]
When I try to call some endpoint like http://pokeapi.co/api/v2/pokemon/25/ and chrome devtools is open, I get a response header error like:

> XMLHttpRequest cannot load http://pokeapi.co/api/v2/pokemon/25/. Request header field X-DevTools-Emulate-Network-Conditions-Client-Id is not allowed by Access-Control-Allow-Headers in preflight response.

It only happens in Chrome, no such problem with Firefox devtools. Is it a Google chrome issue that it is sending a custom header or does it have something to do with the API itself?

Not a big issue, but it would be nice if this could be fixed.

**Comment by phalt** [comment]
@vaikan this looks like a typical CORS issue, I've seen it a lot recently. I think we fixed it for PokéAPI, but maybe we actually did it for another project :see_no_evil:

**Comment by vaikan** [comment]
@phalt well, just realized that this only occurs with Chrome Canary (Version 51.0.2677.0, 64-bit) which I was using to test the API. There is no issue with the recent Chrome Stable release.

**Comment by phalt** [comment]
Awesome, can I close @vaikan ?

**Comment by vaikan** [comment]
@phalt Yes, you can. I don't think this issue will effect most of the developers anyway.
