### ISSUE TITLE
jsonp support

### ISSUE THREAD

**Issue by timlevett** [phalt/pokeapi#155]
As a user that doesn't have a server back end, I would like to be able to utilize JSONP in my application to access this API.

+ Add `callback` parameter that takes in the function name
+ If callback parameter exists, change return type to `text/javascript`

See https://developer.github.com/v3/#json-p-callbacks for an example.

**Comment by phalt** [comment]
It looks like this might be the best solution: http://www.django-rest-framework.org/api-guide/renderers/#jsonp

**Comment by phalt** [comment]
@timlevett is there any reason you want to use JSONP over CORS?

**Comment by timlevett** [comment]
JSONP requires no configuration on the server, where CORS does according to http://enable-cors.org/. You would need to setup CORS on the hosted server so it can accept requests from my app's URL. Seems like a lot of servers to maintain.

**Comment by phalt** [comment]
@timlevett that's just the PokéAPI server though?

**Comment by timlevett** [comment]
Correct.

**Comment by phalt** [comment]
As far as I'm aware CORS is already set up, so you can use that! :) Okay to close this?

**Comment by timlevett** [comment]
Sounds like we have a solution. Thanks for considering.
