### ISSUE TITLE
Should we handle secondary types?

### ISSUE THREAD

**Issue by smasher164** [phalt/pokeapi#156]
In the current data-set for `/type_efficacy.csv`, there is a damage factor for each damage type and target type. However, it doesn't address dual-type pokemon unless the user computes the effectiveness together for both types.

For example, **electric type attacks** (damage_type_id 13) have a damage_factor of 200 (2x) for both **water types** (target_type_id 11) and **flying types** (target_type_id 3). But against **water/flying types**, it would have a damage_factor of 400 (4x). _In this case, we can neither multiply nor sum the damage_factor since it is a multiple of 100. It would have to be converted to a fraction on the client._

Although veekun's data-set is the same, their website deals with secondary types with a query string [veekun.com/dex/types**?secondary=fighting**](http://veekun.com/dex/types?secondary=fighting).

So should we support secondary types in the API itself?

**Possible solutions:**
- Add more types to `/types.csv` beyond 18, for each dual-type combination, and because there is no such thing as a dual-type attack, add the dual-types to the target_type_id column in `/type_efficacy_.csv`.
- Allow querying for secondary type with `?secondary=` or `/type/secondary/`, and compute type information and effectiveness on the server.

**Comment by zaneadix** [comment]
@smasher164 I'm not against the idea of adding a query param for a secondary type. That's pretty clever. We would just need to add a 'quadrupal_damage_to' param in the response.

**Comment by smasher164** [comment]
@zaneadix Cool, I'll see if I can take a crack at it.
