### ISSUE TITLE
Outsourced Data

### ISSUE THREAD

**Issue by mjhayes412** [phalt/pokeapi#161]
Out of curiosity, are we not using any of the [PokemonShowdown data](https://github.com/Zarel/Pokemon-Showdown/tree/master/data)? If not, I could take on the task of extracting data from it, for example the move descriptions.

Would there be any benefit in separating the API and database into two docker containers (possibly three)?  I watched a [video](https://www.youtube.com/watch?v=Pe6a8Jbvi9E) that separated a wordpress instance (gross, I know) and its MySQL database.  It even had a persistent data container that was only ran to create a volume for the MySQL container to reference and that's it!  I mean, how cool is that?!

So my idea of a RESTful API is one that doesn't perform inserts or updates and sends out data lightning fast.  To me, that sounds like [prime indexing time](http://forloop.co.uk/posts/files/3dfeff6a-bd92-4301-8461-27945d8fd378.jpg).  I mean, I'm ready to index ItemGameIndex on its game_index, am I right?

I've been wanting to design a database structure with this particular data (for my personal gain ... I live for relational database structure) but at the same time I really, really want to contribute to this one.  So how do you guys feel about edits to the model?  Would anyone be wiling to mentor me on its current design?  The level of abstraction is awesome .... I think.  It might be asking much but I was wondering if someone could take me under their wing and get me started in making commits.  I really want to see some activity on my profile page :)

**Comment by nimaje** [comment]
We are using the data from [veekun's pokedex](https://github.com/veekun/pokedex).
Do you miss data which is provided by PokemonShowdown? I think we have move descriptions.

This should be a benefit for those who develop with docker, because they could keep the db. (What could the third container be?)
But I don't know how @phalt runs the server (he has hopefully read that you should not use `python manage.py runserver` for productive servers[[1]](https://docs.djangoproject.com/en/1.9/ref/django-admin/#runserver)).

As far as I know there are no inserts or updates outside of `data/v[1|2]/build.py` with the exception of some counting.

**Comment by phalt** [comment]
@mjhayes412 your idea of REST isn't quite right. Give it a bit of research, it's a way of providing an API through `representations` where your `transfer` the `state` without storing any state on the server :)

Also, there are no stupid questions, so never feel afraid to ask anything!

**Comment by zaneadix** [comment]
@mjhayes412 I did not include the pokemon showdown data. I'm not opposed to it but while I was working on the APIs I decided to stay focused on the main series purely for my own sanity. If this is something you would like to dig into I would not discourage you :) 

If you're into card games at all I'd personally love to see some activity driving a PTCG API forward. (NOPRESSURE)
![image](https://cloud.githubusercontent.com/assets/7071557/14677473/ec020282-06df-11e6-991b-c33de7503cbf.png)

**Comment by phalt** [comment]
+1 - let's keep this API focussed on the games. Having too much information can put people off, and V2 is as far as I want to go with adding information.

**Comment by zaneadix** [comment]
@phalt Does this mean there should be a completely separate project for a card game api?

**Comment by phalt** [comment]
@zaneadix I'm tempted by the idea, just to avoid this turning into a "salesforce for Pokémon" :)

**Comment by zaneadix** [comment]
@phalt OH DEAR GOD NO THATS ALL YOU HAD TO SAY
