### ISSUE TITLE
Caching entire API?

### ISSUE THREAD

**Issue by kerbingamer376** [phalt/pokeapi#165]
Is in possible to cache/download the entire api (all the pokemon, moves, items etc) to local .json files?

**Comment by phalt** [comment]
@kerbingamer376 you're more than welcome to use the API to cache results, yes. We don't offer a single endpoint for doing this, as it's not the main purpose :)

**Comment by kerbingamer376** [comment]
But, how would I?

**Comment by phalt** [comment]
@kerbingamer376 given that you can query pages of items, that would be a good way to go. Otherwise, you can query every resource once and store them.
