### ISSUE TITLE
Fuzzy string matching on resources

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#18]
In V1, we can search for Pokémon via name:
```
HTTP GET /api/v1/pokemon/mew
```

This would be nice to have on other resources like types, moves, et cetera, in the V2 api

**Comment by SerenadeX** [comment]
👍🏻

**Comment by zaneadix** [comment]
Taken care of in pull request #53. If a resource has a "name" attribute then it can be used in the path rather than the id/pk

**Comment by bsides** [comment]
I'm sorry for reliving this issue, but is it possible to do what the author talked about? Today, trying parcial names like https://pokeapi.co/api/v2/pokemon/pika/ returns me nothing. Could it be implemented? Or any direction in how to do it?

**Comment by Naramsim** [comment]
The best implementation would be on the client side, with a list of all the pokemon and thus searching there

**Comment by ahester57** [comment]
I have a sort of spell check in my pypoke repo. It's not automcompleted yet
but you could add it. It uses a list of Pokémon but it is only good up to 3
characters off.

**Comment by bsides** [comment]
I do believe normalizing it via frontend and then doing that could do the trick. Thanks for answering!

**Comment by Naramsim** [comment]
Because also if you fuzzy search on the front-end it will be much quicker!
