### ISSUE TITLE
Separated/precompiled website and docs

### ISSUE THREAD

**Issue by ThisIsAreku** [phalt/pokeapi#182]
I think we should split the project into website+docs and api. In my opinion, website and docs should be precompiled and served via nginx instead of python.

The objective is to let python handle only the /api/* urls, and setup nginx as a front proxy to serve static assets

**Comment by phalt** [comment]
Potentially a good idea if the docs did something more than just serve static files. Though I don't see what major benefit this will have, as the docs are static pages anyway? This seems premature optimisation.

**Comment by ThisIsAreku** [comment]
Currently, as docs are templates and markdown files, (I may be unaware of some Django caching) I think those files are parsed when requested and generated by the server.
Sure this is not a priority, but #180 will require client to make more http requests, so it might be good to anticipate.

**Comment by phalt** [comment]
This is true. I'm investigating ways to move away from Django and do more static file serving if I can, which should also help to reduce load.

**Comment by nimaje** [comment]
@phalt you use django's runserver for running the server?
The [docs](https://docs.djangoproject.com/en/1.9/ref/django-admin/#runserver) say you shouden't use it in a production setting (in all caps letters).
Because `gunicorn` is already a dependency of this project (why?).
http://docs.gunicorn.org/en/latest/deploy.html could give ideas to use django + gunicorn + nginx.

**Comment by phalt** [comment]
@nimaje I'm using gunicorn :)

**Comment by nimaje** [comment]
first sentence in the gunicorn docs I linked above:
`We strongly recommend to use Gunicorn behind a proxy server.`
They recommend this against denial-of-service attacks.

**Comment by phalt** [comment]
I am using gunicorn and nginx?
