### ISSUE TITLE
evolution-chain uses inconsistent schema for evolution_details

### ISSUE THREAD

**Issue by zberk** [phalt/pokeapi#188]
Best example to compare is evolution-chain/1 and evolution-chain/34.

The evolution_details property for evolves_to can be null, a single value, or an array. I propose wrapping all values in an array so that the expected type remains consistent.

**Comment by phalt** [comment]
👍 good idea, and a fairly simple task for anyone looking for an easy thing to do :)

**Comment by sargunster** [comment]
Currently running into this issue while working on my Kotlin/Java wrapper for the API. It's tough to work around this in a statically typed language.

Any tips on where in the code I can look to contribute a fix?

**Comment by zberk** [comment]
I am pretty sure the problem is in serializers.py in the pokemon_v2 folder. Search for the EvolutionChainDetailSerializer class (its a big file). Please let me know what you find. Thank you and good luck!

**Comment by sargunster** [comment]
Thanks, I'll let the table building stuff run tonight and check it out (my) tomorrow evening.
