### ISSUE TITLE
Use Django REST Framework for v2 resources

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#2]
Django REST Framework should be used for the new version of the resources, which will eventually depreciate the old version.

**Comment by WToa** [comment]
Is there an estimate time as to when this will be done? I'm looking to use the v2 resources whenever the API for it becomes available for me to access :)

**Comment by phalt** [comment]
Currently trying to find time between work I'm afraid. The intention of making PokeAPI open source was so people could start to contribute to it.

**Comment by phalt** [comment]
Started in #25

**Comment by zaneadix** [comment]
@phalt Do you think this can be considered done since work has started heavily with Django Rest Framework or do you think it should be closed when the task is done?

**Comment by phalt** [comment]
@zaneadix the issue is a bit vague (my bad) so let's close this as it could be misleading.
