### ISSUE TITLE
resource_uri for pokemons in Pokedex api missing a '/' before api

### ISSUE THREAD

**Issue by sayo9349** [phalt/pokeapi#22]
the resource_uri for pokemons in Pokedex responce is missing a '/' before api.
All other calls have their resource_uri starting with a '/' as such;
"resource_uri": "/api/v1/ability/2/"

but the Pokedex responce doesn't
Example request

GET http://pokeapi.co/api/v1/pokedex/1/
Result:

{
  "created": "2013-11-09T15:14:48.957604",
  "modified": "2013-11-09T15:14:48.957565",
  "name": "national",
  "pokemon": [
    {
      "name": "pidgeotto",
      "resource_uri": "api/v1/pokemon/17/"
    },
    ...
    ]
}

**Comment by phalt** [comment]
This is due to a bug in /pokemon/api.py line #46 - the matching is done manually on descriptions whose name contains the name of the Pokémon.

Want to tinker with it and prevent it from happening?

**Comment by phalt** [comment]
V1 is now deprecated, on V2 features and bugs will be fixed.
