### ISSUE TITLE
Abra incorrectly has Kadabra's descriptions along with it's own.

### ISSUE THREAD

**Issue by Shad0wShayd3** [phalt/pokeapi#23]
![capture](https://cloud.githubusercontent.com/assets/2724172/5829030/3207aaf8-a0c9-11e4-99f9-3a491860ca5b.PNG)

**Comment by TheIronDeveloper** [comment]
This exposes a different problem. The search to include descriptions searches for inclusiveness, not an exact match.  Another example of this bug being relevant is pokemon #304, Aron (which will provide descriptions for volcarana as well.)

I'm not a python guy, so I'm a little slow in finding the pain point, but I'll submit a PR if I catch it.

**Comment by phalt** [comment]
@TheIronDeveloper this is exactly what is causing the issue. It's looking for values with  the name of the pokémon in, so Abra will get Kadabra's name because: Kad**abra**.

It needs some regex magic work instead of a simple icontains

**Comment by Shad0wShayd3** [comment]
Line 46 in [pokemon/api.py](https://github.com/phalt/pokeapi/blob/master/pokemon/api.py) is where that pain point is. I could fix it if I actually knew what was doing what. (My knowledge of django is spotty)

The build_descriptions function passes "name" which is what icontains is looking for within the Description.objects.filter QuerySet. My only problem is not knowing what that QuerySet actually is.
For instance, if that QuerySet is "kadabra_gen_4", the easiest fix would just be to compare length with something like

```python
if (len(str(Description.object.filter))-6) == len(name):
   ds = Description.objects.filter(name__icontains=name)
   lst = []
   ........
```

And so on. This would cause it so that only Pokemon with names the same length of as what you're looking for (subtracting 6 for the generation tag). Making Abra (4) and Kadabra (7) unable to be matched, while comparing Abra to Aron and Uxie. I figure this will work, but I have no actual means of testing it, since I have no idea what icontains is looking in and I can't get the API working outside of the stuff in [dev_data.json](https://github.com/phalt/pokeapi/blob/master/pokemon/fixtures/dev_data.json).

**Comment by phalt** [comment]
This is a good starting point for the filtering: https://docs.djangoproject.com/en/1.8/ref/models/querysets/#id4

And the regex in particular: https://docs.djangoproject.com/en/1.8/ref/models/querysets/#regex

Django knowledge isn't important here, string interpolation is what will solve this. Can you write a regular expression that matches on strings correctly? The name string is always something like this:

```
"abra_gen_1"
"abra_gen_6"
"kadabra_gen_1"
"kadabra_gen_4"
```

**Comment by Shad0wShayd3** [comment]
So [here's a super simple fix to the build_descriptions function](https://github.com/Shad0wShayd3/pokeapi/blob/master/pokemon/api.py). It still uses icontains, but before appending the list, it checks to see if the name matches using the same method I described above, checking to see if the name of the Pokemon it's adding to the list is the same length as the name of the Pokemon it's looking for.

Let me know if this works, and if not I'll try something else.

**Comment by TheIronDeveloper** [comment]
I'll need to look into the syntax of icontains, but I'd have to imagine you can do a regex like:

`'/^' + name + '/'`

**Comment by phalt** [comment]
Okay, this is the last thing I will be fixing on V1, all other features requests for V1 are being deprecated and closed.
