### ISSUE TITLE
404 page illegible 

### ISSUE THREAD

**Issue by James-Oldfield** [phalt/pokeapi#27]
Albeit a small issue, thought I would raise this incase it's been overlooked - The 404 page is illegible due to insufficient margin from the navbar in the current state, see photo;

![screenshot 2015-03-02 20 43 41](https://cloud.githubusercontent.com/assets/7990316/6450036/fe93db6e-c11c-11e4-8b77-9766535622ec.png)

**Comment by hughrawlinson** [comment]
Pull request @James-Oldfield! :shipit:

**Comment by phalt** [comment]
@James-Oldfield Feel free to fork and make the css changes :)

**Comment by zaneadix** [comment]
Taken care of in UI changes
