### ISSUE TITLE
Critical Hit Ratio & Priority?

### ISSUE THREAD

**Issue by aindurti** [phalt/pokeapi#28]
How does one go about differentiating for **moves** with either increased critical hit ratios, or with increased/decreased priority?

  * **EX 1:** Find all pokemon that **can learn** Skill Swap **AND** any move with an increased critical hit ratio *(eg. Psycho Cut, Razor Wind, etc....)*
  * **EX 2:** Find all pokemon that **can learn** an offensive, increased priority move *(eg. Mach Punch, Feint, Pursuit, etc....)*

(I'm assuming that because this is RESTful, we'll just be passing from resource to resource. The first resource for a move, and the second for a pokemon. I just don't understand how to easily differentiate for these categories.)

Thank You

**Comment by aindurti** [comment]
Alright, so I wrote a python script for the first one that **doesn't** use the API, the reason being that the objects returned by the GET responses don't seem to allow collections of moves/pokemon. Ultimately chaining these requests together would be optimal to find outputs that are unique to specially-trained teams. I still use the ***CSV*** files, however, as they and pandas were key to this script.

[Example 1 Script](https://gist.github.com/aindurti/5d1260416cee623e0829#file-critswap-py)
```python
import pandas as pd

# retrieve move ids from crit rates
a = open('move_meta.csv')
av = pd.read_csv(a)
av = av[['move_id','crit_rate']]
av = av[(av['crit_rate'] > 0)]
av = av['move_id'].tolist()

# retrieve move id from move identifier
b = open('moves.csv')
bv = pd.read_csv(b)
fz = bv
bv = bv[['id','identifier']]
bv = bv[(bv['identifier'] == 'skill-swap')]
bv = bv['id'].tolist()

# retrieve pokemon id from move id
c = open('pokemon_moves.csv')
cv = pd.read_csv(c)
cv = cv[['pokemon_id','move_id']]
cv = cv[(cv['move_id'] == bv)]
cv = cv.drop_duplicates(cols='pokemon_id')
cv = cv['pokemon_id'].tolist()

# retrieve pokemon ids from move ids
d = open('pokemon_moves.csv')
dv = pd.read_csv(d)
dv = dv[['pokemon_id','move_id']]
dv = dv[(dv['move_id'].isin(av))]
# retrieve pokemon that know skill swap as well
dv = dv[(dv['pokemon_id'].isin(cv))]
dv = dv.drop_duplicates(cols=['pokemon_id', 'move_id'])

# retrieve pokemon identifiers and move identifiers

# first pokemon identifiers
e = open('pokemon.csv')
ey = pd.read_csv(e)
ey = ey[['id','identifier']]
ey = ey.set_index('id')['identifier'].to_dict()
ey = dv.replace({'pokemon_id': ey})

# second move identifiers
fz = fz[['id','identifier']]
fz = fz.set_index('id')['identifier'].to_dict()
fz = ey.replace({'move_id': fz})

final = fz
final.columns = ['Pokemon','Move']
final = final.set_index('Pokemon')
final.to_html('finalfile.html')

print final
# print fz
# print ey
# print dv
# print dv
# print cv
# print bv
# print av
```

**Comment by zaneadix** [comment]
Sorry No one has ever gotten back to you on this issue. Honestly I've looked over what you've posted and I'm not 100% sure exactly what your issue is. Is this still something concerning you? I'd like to help if I can
