### ISSUE TITLE
description/1/ is 404ing

### ISSUE THREAD

**Issue by TheIronDeveloper** [phalt/pokeapi#29]
Hey, my integration tests happened to catch an issue with `description/1/`.

**Note**:
`description/2/` still works

**Comment by phalt** [comment]
Yup, this isn't a problem? Description with an ID of 1 simply does not exist. There is no explicit numbering system or rule saying that resources starts at ID 1 and increment one value at a time.

**Comment by TheIronDeveloper** [comment]
The documentation should be updated then:

![screen shot 2015-04-04 at 11 29 56 am](https://cloud.githubusercontent.com/assets/364028/6994020/faddbb7e-dabd-11e4-839e-ca61a1b348c6.png)

**Comment by phalt** [comment]
:+1:
