### ISSUE TITLE
[Question] Limited dataset upon installation

### ISSUE THREAD

**Issue by TheIronDeveloper** [phalt/pokeapi#31]
Hey there. I've forked this project, ran the make steps, and am running into an issue where I see a limited dataset (`dev_data`).   How do I populate the rest of the information locally?

**Comment by phalt** [comment]
It's a test data set, so it's just test data. There are scripts for populating the database but they're not well documented. Please keep in mind I made this project over one weekend for a hackathon and t'was never intended to be so popular :)

**Comment by TheIronDeveloper** [comment]
Thats totally understandable, this is an awesome project, especially for a weekend hack! :)
