### ISSUE TITLE
Description doesn't match the correct game/generation

### ISSUE THREAD

**Issue by ErazerBrecht** [phalt/pokeapi#34]
As example Charmander:

Description Gen 1 Red: 
http://pokeapi.co/api/v1/description/48/
"Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."
This seems to be correct

Description Gen 2 Crystal: 
The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when CHARMANDER is happy, and blazes when it is enraged.
This is the description of Sapphire and Ruby(Gen 3)

So I kept searching after the one of Gen 2 (GSC)

I found the one from gold @ http://pokeapi.co/api/v1/description/50/
But It says it's from Pokémon Red
So this is incorrect information at your database

Keep up the good work!

**Comment by ErazerBrecht** [comment]
![image](https://cloud.githubusercontent.com/assets/6287467/7034859/d5f0dc60-dd83-11e4-8d25-2b31b45815d7.png)

The datafile seems to be correct

Used this site as reference: http://pokemondb.net/pokedex/charmander

**Comment by phalt** [comment]
I must just loaded the data incorrectly. API V1 is now frozen, no no changes are being made to it. I'll make sure this is fixed for V2
