### ISSUE TITLE
Cache-Control / ETag headers

### ISSUE THREAD

**Issue by berwyn** [phalt/pokeapi#36]
I think using proper HTTP caching could be a great boon to client-side developers, as documented [here](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en#validating-cached-responses-with-etags)

I'm more than willing to contribute this, but not at a computer right now, so thought I'd document it for when I get home :p

**Comment by phalt** [comment]
can definitely add this to V2

**Comment by lsteel** [comment]
Not sure if doing this would solve this issue, but when I try to make client side requests from Safari I get:
`Failed to load resource: Request header field Cache-Control is not allowed by Access-Control-Allow-Headers.`
`XMLHttpRequest cannot load http://pokeapi.co/api/v2/pokemon/?limit=151. Request header field Cache-Control is not allowed by Access-Control-Allow-Headers.`

I tried changing http to https, but that only worked for about 6-7 calls. Then it gave me this error again.
