### ISSUE TITLE
Add CORS to v2 API

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#4]

**Comment by rdmurphy** [comment]
Was gonna jump in and help, then realized it may have already happened. :grin: 

https://github.com/phalt/pokeapi/blob/1b59324630c1ce2c56a97c1f8c80da932d6bcf7d/requirements.txt#L7
https://github.com/phalt/pokeapi/blob/1b59324630c1ce2c56a97c1f8c80da932d6bcf7d/config/settings.py#L141-L145

**Comment by phalt** [comment]
Awesome! Let's close this :)
