### ISSUE TITLE
Types don't have "resistance"

### ISSUE THREAD

**Issue by addcms** [phalt/pokeapi#42]
Each type has a "resistance" member (array) but no types have been assigned any "resistances" meaning all "resistance" arrays are empty.

**Comment by phalt** [comment]
API V1 is deprecated, so we won't be adding this data to V1. Contribution to V2 is welcome!

**Comment by addcms** [comment]
What is the URL and GitHub repo for V2? I can't seem to find them.

**Comment by phalt** [comment]
This is the repo for V2 - just very little work has been done. See the commit history :)

**Comment by addcms** [comment]
Wait so i submit a bug saying information is missing, you then tell me that this version has been discontinued and therefore the bug wont be fixed on this repo, I then ask where the new one is, and you say this is it... Im so confused... Is this the repo that the bug fix would be applied to or not? And what is the URL for V2. As in where is it being hosted that I can consume the data?

**Comment by phalt** [comment]
Sorry for the confusion:

- This is the repository for the entire project, including version two, which is in progress. We're hosting both API versions on the same project. That's fairly normal practice.
- Version 2 is not live yet, so no URL exists.
- You're more than welcome to contribute to building version 2. We have a huge amount of data models that have been added, but we have not yet linked up the API endpoints.
