### ISSUE TITLE
Add a Pre-Evolution attribute

### ISSUE THREAD

**Issue by CCGLP** [phalt/pokeapi#45]
Pretty self-explanatory title, I think it's a easy thing to add, and can be useful to link pokemon of the same "family".

It can work pretty much as the "evolutions" do.

**Comment by zaneadix** [comment]
I would probably suggest mentioning this in [Veekun's](https://github.com/veekun/pokedex) repo. The data here for v2 has been pulled 100% from there.

**Comment by CCGLP** [comment]
Thank you, I'll do it later!

**Comment by zaneadix** [comment]
The new v2 Pokemon resources have an "evolves_from_species" attribute as well as a link to an Evolution Chain Resource that will give all related evolution information.
