### ISSUE TITLE
catch_rate always 0

### ISSUE THREAD

**Issue by D1amond** [phalt/pokeapi#46]
It seems that every pokemon data returned by http://pokeapi.co/api/v1/pokemon/x has a catch rate of 0, which is incorrect.

**Comment by DiamondIceNS** [comment]
Sounds like that's v1 of the project, which was depreciated.  Bugs in v1 of the project will not be patched.

**Comment by zaneadix** [comment]
Yep. This is taken care of in v2 already. Dig through the code and help out where you can :)
