### ISSUE TITLE
List possible IDs

### ISSUE THREAD

**Issue by cfjedimaster** [phalt/pokeapi#47]
Forgive me if this already exists, but is there a way to get a list of valid IDs for a resource? So for example, if I want to get all Pokemons, I'd need the list of valid IDs first.

**Comment by zaneadix** [comment]
Sorry for a late response. This should work in v2. For example, making a call to api/v2/pokemon would return 
```
{
	count: 784,
	next: "http://localhost:8000/api/v2/pokemon/",
	previous: null,
	results: [
		{
		name: "bulbasaur",
		url: "http://localhost:8000/api/v2/pokemon/1/"
		},
		{
		name: "ivysaur",
		url: "http://localhost:8000/api/v2/pokemon/2/"
		},
...
```
If you wanted a list of all possible pokemon you would just need to add a limit query param like so
api/v2/pokemon?limit=1000

**Comment by cfjedimaster** [comment]
Muchas gracias.
