### ISSUE TITLE
Use possibly better json document to get pokemon data.

### ISSUE THREAD

**Issue by aarohmankad** [phalt/pokeapi#49]
[This Gist](https://gist.github.com/odanado/70032b84d097349550c5) has a **lot** of data that pokeapi doesn't have.

**Comment by phalt** [comment]
Agreed, but this will required quite a large database restructure.

**Comment by aarohmankad** [comment]
do you think there's a way that we can merge the two datasets?

**Comment by phalt** [comment]
It depends. I consider the current version of PokéAPI to be deprecated, so I would not suggest we add new data to that. V2 has been ongoing for almost a year now, due to lack of time and effort on my part, but I believe we have a fairly up to date and better data model already built.

**Comment by zaneadix** [comment]
As far as I can tell this is only the pokemon data right? Its also limited to their base stats, attacks, types and names. I don't even see national id. This is just a small portion of what is in v2 already.

**Comment by zaneadix** [comment]
Closing this issue as the v2 dataset is quite a bit larger than what is in the recommended gist.
