### ISSUE TITLE
Is there any sort of quota?

### ISSUE THREAD

**Issue by Oza94** [phalt/pokeapi#51]
Hello,

Is there any sort of quotas that we should respect in client applications? I didn't see any relevant part in the documentation.

My use case is: I'll use http://pokeapi.co/ in my personal project to fill my database with initial attributes (for pokemons, moves, items, ect.), this will likely fire hundreds API calls in a matter of seconds without throttle. Should I do something on my side to be respectful?

Great job anyway, thanks to the contributors!

**Comment by phalt** [comment]
It's not really clear, but it is mentioned in the top section of the docs: 300 requests per resource per day. Cache all the requests you make :)
