### ISSUE TITLE
404 result in api not in json format

### ISSUE THREAD

**Issue by vincentnacar02** [phalt/pokeapi#59]
i suggest result to {"error":"404 not found"} , or we can add error responses :)

**Comment by phalt** [comment]
@vincentnacar02 Why not the HTTP response status?

**Comment by vincentnacar02** [comment]
if you use error responses in json format its easy to integrate , and we can extend error messages, (e.g http://pokeapi.co/api/v1/pokemon/99999/ then posible response is {"error": "Pokemon 99999 not found in our database"} )

**Comment by phalt** [comment]
@vincentnacar02 I'm still confused as to why the HTTP response status isn't suitable for you?

**Comment by vincentnacar02** [comment]
I tell you later . Thanks
