### ISSUE TITLE
Naming inconsistency for lightningrod.

### ISSUE THREAD

**Issue by RainingChain** [phalt/pokeapi#65]
Every ability name follows the same naming convention (lowercase with hyphen). 
Ex: pure-power, rock-head, heavy-metal, minus.

Following this convention, the ability Lightning Rod should be named lightning-rod but in the API, it is named lightningrod.
Ex: pokemon/112

**Comment by zaneadix** [comment]
@RainingChain Sorry for the late response. This wont be fixed for v1as its been deprecated but is taken care of in v2. Hoping to have something up soon.
