### ISSUE TITLE
Species strings are empty except for Bulbasaur

### ISSUE THREAD

**Issue by nolanlawson** [phalt/pokeapi#67]
If you check out http://pokeapi.co/api/v1/pokemon/2/, you'll see:

```
"species": ""
```

Whereas for http://pokeapi.co/api/v1/pokemon/2/, you see:

```
"species": "seed pokemon"
```

Bulbasaur seems to be the only one with its `species` listed.

**Comment by nolanlawson** [comment]
Ah, I just looked through the CSVs, and it seems like the species data just isn't in there. That would explain it. :)

**Comment by zaneadix** [comment]
@nolanlawson Sorry for the late response. This is something we have taken care of for V2. Hoping to have something up soon.
