### ISSUE TITLE
Add a full test suite

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#7]
So far, there are no complex tests to ensure the correct data is given.

Let's add a full test suite for the API and models.

**Comment by zaneadix** [comment]
@phalt 
What are the parameters we're looking for with these tests? I've spent a few hours digging into django/rest framework testing docs and have got some basics going but haven't been done a ton of unit testing and am not really sure to what level we should be digging for validation.

First thought is to take a look at any api resources we have and write a test that will build out entries in all the tables the resource pulls data from, call the api to get the resource and make sure the fields match what would be expected.

Maybe also add a second object and make sure that "list" calls are returning both objects.

Does that sound about right? You think we need anything else? Is calling the api enough validation that objects are being added to the database the way we expect?

**Comment by phalt** [comment]
@zaneadix having good integration tests is a great start. We care about the data given by the API, so we should make sure that is as we expect. Tests that call each resource comparing expected results and actual results is good.

**Comment by zaneadix** [comment]
Progress made in pull request #62.
