### ISSUE TITLE
Missing Sprites for Pokemons

### ISSUE THREAD

**Issue by hhzplst** [phalt/pokeapi#71]
For example:

pokemon/10016/ returns "Sprites" as an empty array, sprite/10016 returns 404

Similar issue with id 10010, 10033 etc.

**Comment by zaneadix** [comment]
@hhzplst Sorry for getting back to you late on this. V1 is missing a handful of things but has been deprecated. This is an issue that will be taken care of v2.

**Comment by domenicoblanco** [comment]
Sorry for writing here, but I thought that it would be better instead of creating a duplicate.
This problem is still present in v2

**Comment by Naramsim** [comment]
yeah, we don't have those spites, I guess

**Comment by domenicoblanco** [comment]
Nope, they're available by another link obtainable inside ["forms"][0]["url"]. For example, for Alolan Marowak, the url is https://pokeapi.co/api/v2/pokemon-form/10217
and the sprites are in ["sprites"]
