### ISSUE TITLE
[Feature Request] SSL Support

### ISSUE THREAD

**Issue by vinkla** [phalt/pokeapi#72]
What about adding SSL? Cloudflare is offering them [for free](https://www.cloudflare.com/ssl/).

**Comment by andreicek** [comment]
With the Let's encrypt public beta this is now trivial. +1 on this!

**Comment by phalt** [comment]
I'm planning on spinning up the V2 work that has been done this year over the Holiday period. I'll try and get SSL working too :)

**Comment by andreicek** [comment]
If you need any help do not hesitate to ask me :)

**Comment by vinkla** [comment]
@phalt :+1:

**Comment by smasher164** [comment]
+1 to the SSL support!

**Comment by phalt** [comment]
Currently rolling over to cloud flare and SSL :)

**Comment by vinkla** [comment]
@phalt :+1:
