### ISSUE TITLE
User proper data types for fields

### ISSUE THREAD

**Issue by basharov** [phalt/pokeapi#74]
Some fields with number values, like `weight`, `height`, are in quotes, becoming strings, but others are just unquoted numbers, like `attack`. Is it done intentionally or is it a bug?

Should number values be numbers, not strings?

Thanks!

**Comment by zaneadix** [comment]
Yeah this isn't ideal but unfortunately V1 has been deprecated. This has been taken care of in V2 which we hope to have up soon.

**Comment by phalt** [comment]
@basharov the original behaviour was to have everything be a string. V2 shall have more appropriate datatypes.
