### ISSUE TITLE
Let's do the card game too!

### ISSUE THREAD

**Issue by zaneadix** [phalt/pokeapi#76]
I love the video games. I've probably burned more hours playing pokemon that any other game in my life. But my true passion lies in the card game. I had to quit the card game a few years ago because it took over my life but I still check pokebeach every day and read articles on the metagame. I would love to be able to give back to the card game community through pokeapi. 

Does anyone know of an open source project that catalogues the cards in the same way that veekuns pokedex does the games? I'll start looking but I would love some help figuring out how to get a data set together.

**Comment by zaneadix** [comment]
https://www.npmjs.com/package/pokemon-tcg-scraper

This could be interesting if we have no other options

**Comment by phalt** [comment]
I always had plans to do this as I used to play the card games to death (came 1st in quite a few local tourneys back in 2012/13 :muscle: )

I think this could be a good extra project!

**Comment by zaneadix** [comment]
Awesome. Maybe this could stretch over 2016 haha.
Found this a couple hours ago.
https://github.com/Guernouille/pokeplayer
looks promising. its db code for this website
http://pokeplayer.com/cardex/search

**Comment by nicksarafa** [comment]
Stumbled upon this open issue. Anybody find a reliable API for the Pokemon Trading Card game?

**Comment by tdmalone** [comment]
@nicksarafa This issue was probably closed back when PokeAPI almost shut down - a lot of issues got closed around the time.

I don't know of anyone around currently who would be up for working on this but if you are, happy to reopen!

**Comment by Gamer2020** [comment]
https://pokemontcg.io

Get Outlook for Android

________________________________
