### ISSUE TITLE
Dealing with linking markup in text fields

### ISSUE THREAD

**Issue by zaneadix** [phalt/pokeapi#77]
Veekun's data has some markup used in their pokedex. Do we want to leave this in the data we're serving? Here's an example.
```
Absorbs []{type:water} moves, healing for 1/4 max [HP]{mechanic:hp}.
```
Should we scrub this sort of thing out or leave that up to the user? The only reason I would consider leaving it in is that it could be useful to a user.

**Comment by phalt** [comment]
This seems very specific to Veekun's data, I don't recognise the syntax. If it is bespoke we should try and remove it.

**Comment by zaneadix** [comment]
Ok cool. I'll see if I can work on removing it in during the db build.
