### ISSUE TITLE
Build V2 models to reflect csv in data/v2/csv

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#8]
The V2 resources should map directly to the csv files in ```data/v2/csv```, to ensure easier mapping data and especially when we need to update the models.

**Comment by zaneadix** [comment]
Have you made a lot of progress on this task? I'm not a Django guy t all really so I've been playing around with this to get down the Model layer and I'm wondering if I could be any help to flesh it out legitimately.

**Comment by phalt** [comment]
@zaneadix I got an awful lot of emails from you last night, testing things? Please remove my email next time.

I've made almost no progress on this as I'm quite busy. I made this open source so people could contribute but alas, it seems no one actually wants to now they can :D You're free to make a start.

**Comment by zaneadix** [comment]
Sorry again about those dumb emails. Just wanted To give an update so anyone who wants to jump in can message if they want to. I'm also putting some time into the database build script just to test the models out. I've got the abilities in place and am going to go through to find where I can abstract similar models to streamline things.

**Comment by phalt** [comment]
@zaneadix wow nice, thanks! This would be amazing if you could. Feel free to open up a Pull Request and I can review the work you've done so far and offer advice.

**Comment by zaneadix** [comment]
Pull request #35 should hopefully knock this issue out. Some more data can be pulled in from veekun (Items, Berries, Regions) but up to this point there should be models for everything else.

**Comment by zaneadix** [comment]
Taken care of in pull request #40
