### ISSUE TITLE
Are the names of Pokèmon/moves/etc. in other languages available somehow?

### ISSUE THREAD

**Issue by skylarjhdownes** [phalt/pokeapi#83]
Presumably collecting translations for "all the things" would be prohibitively time consuming, but pokèmon names specifically could be useful.  Hello all, by the way.

**Comment by zaneadix** [comment]
Hello, @skylarjhdownes. Hopefully very soon we'll have some changes up that will give you access to most everything in different languages. Thankfully veekun's pokedex project we snatched the data from has a ton of translations (not all quite there but quite a damn bit). A small dream of mine is that people will get interested enough in fleshing pokeapi out that they'll contribute back to veekun's project and give us tons of translations.

**Comment by Animostas** [comment]
I speak Japanese and I'd love to help out implementing the API in Japanese, could I have some guidance on how I would start doing that?

**Comment by skylarjhdownes** [comment]
I'm new around here, but I would assume that you want to contribute to [veekun's Pokèdex project](https://github.com/veekun/pokedex) since that's where the data is coming from.  Looks like the language is denoted in the local_language_id column in many of the .csv files.  1 seems to be Japanese, and 9 seems to be English.

Am I right in guessing that Pokeapi will continue to use the latest data from there/doesn't keep it's own separate data?

**Comment by zaneadix** [comment]
That's correct @skylarjhdownes. Contributing back to Veekun's translations would be the goal. A lot of resources have Japanese translations @Animostas but not all (I believe) so by all means contribute there what you can.

Ideally we would be able to update with new data from veekun every now and then. Definitely if there are big releases (like new games) or if some big error were to pop up in their data.

**Comment by carab** [comment]
Hello there,

I can't find the "names" property for Pokémons the the API, as you can see there :
http://pokeapi.co/api/v2/pokemon/1/

However, I do find the translations in veekun's Pokédex : 
https://github.com/veekun/pokedex/blob/master/pokedex/data/csv/pokemon_species_names.csv

Is there a reason to this ?

Thank you for your time.

**Comment by nimaje** [comment]
@carab how about read the [docs](http://pokeapi.co/docsv2/).
Read about the [base model](http://pokeapi.co/docsv2/#pokemon-species) of pokémons.

**Comment by carab** [comment]
Indeed I didn't see there was a pokemon-species resource, it's actually consistent with veekun's Pokédex.
Thanks ;)
