### ISSUE TITLE
Location of all Pokemon

### ISSUE THREAD

**Issue by shubshub** [phalt/pokeapi#89]
Would be really great if we could get a Database of where each Pokemon can be found in every game It would also allow me to further my 3DS Web App Pokedex

**Comment by zaneadix** [comment]
Shouldn't be much longer till V2 is up. This information will definitely be available. You can checkout the V2 markdown docs to get an idea of how this looks.

https://github.com/phalt/pokeapi/tree/master/pokemon_v2#pokemon-1
Checkout "location_area_encounter" on the pokemon resource. This will be an array of all possible encounters across versions of the games. You could also check out

https://github.com/phalt/pokeapi/tree/master/pokemon_v2#location-areas
and see the "pokemon_encounters" parameter to see pokemon encounters per area. Is this the kind of information you're looking for?

**Comment by nimaje** [comment]
The api and docs are already online available at http://beta.pokeapi.co.
This would be the suggested docs:
http://beta.pokeapi.co/docsv2/#pokemon
http://beta.pokeapi.co/docsv2/#location-areas

**Comment by zaneadix** [comment]
Oh I didn't think we were posting the beta url publicly. Figured we were
gonna wait till it was pushed to the server root

**Comment by nimaje** [comment]
I thought this beta is for testing the new ui and the api v2 in publicy, because private could everybody test this with a clone of the repo, but @phalt has to decide this.
Sorry if the url were not meant to be public, but it is also mentioned at https://github.com/phalt/pokeapi/pull/81#issuecomment-171242003

**Comment by phalt** [comment]
@nimaje The beta is a... beta. It's gonna be incomplete and we'll kill the url eventually so don't use it for anything but testing the API right now :)

**Comment by nimaje** [comment]
Yes I should have mentioned this when I wrote my comment.
If I understand @zaneadix correctly he wants to know whether the beta is for *public testing* or not.

**Comment by phalt** [comment]
@nimaje sorry.

I've not directly advertised it but the people I've told about it I've mentioned that it is in beta and not to consider it final.

**Comment by nimaje** [comment]
Now I have edited the comment to explicit mentioned the beta status.
