### ISSUE TITLE
Node JS promise wrapper for V1 and V2!

### ISSUE THREAD

**Issue by TheTommyTwitch** [phalt/pokeapi#91]
Hey I just built a wrapper that uses promises in node.js a few days ago for the v1 api. The link to the repo is:  https://github.com/TheTommyTwitch/pokedex-promise

I just started on the v2 wrapper it can be found here: https://github.com/TheTommyTwitch/pokedex-promise-v2

**Comment by phalt** [comment]
@TheTommyTwitch awesome! When you've got it finished, feel free to make a pull request adding the link to it in the docs!
