### ISSUE TITLE
Statistics on About page need updating

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#92]
This should be a nice and easy ticket for someone who wants to get started with open source.

The data on the About page (http://pokeapi.co/about) in the "How much information is stored here?" section is missing V2 data.

The statistics should display a count of all the new models we've added in V2, and a total of all of those rows. The code is pretty simple for this and can be found here:

https://github.com/phalt/pokeapi/blob/master/config/views.py#L241

It appears some of the content has already been calculated, it just hasn't been displayed on the template yet!

**Comment by zaneadix** [comment]
This should be accounted for. 
<img width="963" alt="screen shot 2016-02-08 at 1 22 39 pm" src="https://cloud.githubusercontent.com/assets/7071557/12894831/2940de40-ce67-11e5-9872-213f05c2e69e.png">
Maybe it should be shown in a more obvious place?

**Comment by phalt** [comment]
@zaneadix Ah good point. Though I have noticed the lists of items below it are out of date now, and could do with the information from V2. This is just a nice to have, and I think it would be a good first ticket for someone who's not done open source / python / django before :D

**Comment by LawlietBlack** [comment]
Hi all! I've been learning web development in earnest independently for about a year now and I've loved working with your data! [pokedex.lawlietblack.com](http://pokedex.lawlietblack.com) is an item on my portfolio that I'm particularly proud of and that I plan on expanding more :) . In the meantime, I've been learning python and django and wanting to contribute to open source, so I figure this is the perfect place to start. I'm currently building the database locally and familiarizing myself with the project, and this issue sounds like as good of a place to start as any :)

**Comment by phalt** [comment]
@LawlietBlack good luck! Feel free to ask questions if you get stuck :)

**Comment by LawlietBlack** [comment]
#136 This should do it
