### ISSUE TITLE
/v2/nature/{id|name} returns 500 error

### ISSUE THREAD

**Issue by bdchauvette** [phalt/pokeapi#93]
So I started building a JS wrapper for the API, and it seems like the `/v2/nature/{id|name}` endpoint is serving up 500 errors :(

All the other endpoints  -- including the `/v2/nature/` resource overview one -- seem to be working fine, though!

**Comment by phalt** [comment]
@bdchauvette thanks for the bug report :) We'll look into it this week!

**Comment by cyborgorange** [comment]
This is still broken

http://pokeapi.co/api/v2/nature/1/

**Comment by phalt** [comment]
@cyborgorange thanks, we can only work on this so fast, sorry for the fuss!

**Comment by phalt** [comment]
Should be fixed now :)
