### ISSUE TITLE
What happened to sprites?

### ISSUE THREAD

**Issue by ramirs** [phalt/pokeapi#95]
I just stumbled onto this API last week and after the update, I was shocked to see you guys removed sprites from the API entirely.

I don't know if this is the right way to get in touch, but what was the reasoning / motivation for destroying some parts of the API, rather than just re-organizing data and adding things in?

**Comment by phalt** [comment]
@ramirs Sprite data has not been removed - the entire V1 API is still available.

We're trying to figure out how to add sprite data to the V2 API at the moment using new images :)
