### ISSUE TITLE
The v2 docs contain a few typos

### ISSUE THREAD

**Issue by PoroCYon** [phalt/pokeapi#97]
* **[Pokemon->Pokemon](http://pokeapi.co/docsv2/#pokemon):** `pokeball's` should be `pokeballs`
* **Pokemon->Pokemon->moves, ->species**: links are broken, you seem to have missed a `[` in the Markdown thingy.
* Shouldn't the plural of `pokédex` be `pokédices`? ([because `pokédex`is a portmanteau of `pokémon` and `index`](https://en.wikipedia.org/wiki/Gameplay_of_Pok%C3%A9mon#Pok.C3.A9dex), and the plural of the latter is `indices`.)

Fyi, the TeX-style growth rate formula is awesome.

**Comment by nimaje** [comment]
``pokédex`` is a new word and those from wikipedia don't know an official plural (https://en.wikipedia.org/wiki/Talk:Pok%C3%A9dex#Plural).
*If* it was ``pokémonindex`` the plural should be ``pokémonindices``.

**Comment by phalt** [comment]
@PoroCYon feel free to make a pull request :D

**Comment by PoroCYon** [comment]
@phalt I'll do this, I couldn't find the docs before opening this issue.
